spring:
  datasource:
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5432/jobtrackingsystem}
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver